"""refactor school teacher relationship

Revision ID: 00c4a17f6cae
Revises: fa7aa6854887
Create Date: 2023-10-14 09:25:24.501404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c4a17f6cae'
down_revision = 'fa7aa6854887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
