"""refactor school teacher relationship

Revision ID: 00d2e113dc2e
Revises: b8e07569caba
Create Date: 2023-10-14 09:39:56.568284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d2e113dc2e'
down_revision = 'b8e07569caba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_school_id_fkey', 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'school_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teacher_school_id_fkey', 'teacher', 'school', ['school_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
