"""chore : add status to project

Revision ID: 06b22b3fa353
Revises: 697ef4a49b9d
Create Date: 2024-02-08 13:59:44.771015

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '06b22b3fa353'
down_revision = '697ef4a49b9d'
branch_labels = None
depends_on = None


def upgrade():
    activity_status_enum = sa.Enum('open', 'completed', name='status')
    activity_status_enum.create(op.get_bind())
    op.add_column('project_activity', sa.Column('status', activity_status_enum, nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_activity', 'status')
    # ### end Alembic commands ###
