"""refactor : restructure project

Revision ID: 176dbff519d3
Revises: feb5237f2c46
Create Date: 2023-11-05 21:07:33.376411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176dbff519d3'
down_revision = 'feb5237f2c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('lead_teacher', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('supporting_teachers', sa.JSON(none_as_null=True), nullable=True))
    op.drop_column('teacher_project', 'teacher_position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_project', sa.Column('teacher_position', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.drop_column('project', 'supporting_teachers')
    op.drop_column('project', 'lead_teacher')
    # ### end Alembic commands ###
