"""update school manager

Revision ID: 1bd42e844ec0
Revises: 9bd4fef52476
Create Date: 2023-09-20 07:47:36.737915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd42e844ec0'
down_revision = '9bd4fef52476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_admin_id_fkey', 'role', type_='foreignkey')
    op.add_column('school_manager', sa.Column('_gender', sa.String(length=250), nullable=True))
    op.drop_column('school_manager', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_manager', sa.Column('gender', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('school_manager', '_gender')
    op.create_foreign_key('role_admin_id_fkey', 'role', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###
