"""chore : add subject matter

Revision ID: 1c03c51ecbab
Revises: ba72be53e009
Create Date: 2023-11-10 10:44:17.533873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c03c51ecbab'
down_revision = 'ba72be53e009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('subject_matter', sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'subject_matter')
    # ### end Alembic commands ###
