"""change permission model to passive_deletes True

Revision ID: 1c5392529b3e
Revises: aeb9b87cc099
Create Date: 2023-10-14 16:33:24.254936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5392529b3e'
down_revision = 'aeb9b87cc099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
