"""remove faq

Revision ID: 24369779cc5c
Revises: ecc33f9f7f98
Create Date: 2024-02-22 21:24:21.541528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24369779cc5c'
down_revision = 'ecc33f9f7f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FAQ')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FAQ',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name='FAQ_school_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='FAQ_pkey')
    )
    # ### end Alembic commands ###
