"""chore : update school role, learning-group, project models

Revision ID: 24a14f82ec73
Revises: ed67855975b1
Create Date: 2023-10-23 17:54:34.714041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a14f82ec73'
down_revision = 'ed67855975b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_teacher_id_fkey', 'project', type_='foreignkey')
    op.drop_constraint('project_student_id_fkey', 'project', type_='foreignkey')
    op.drop_column('project', 'teacher_id')
    op.drop_column('project', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('project_student_id_fkey', 'project', 'student', ['student_id'], ['id'])
    op.create_foreign_key('project_teacher_id_fkey', 'project', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
