"""chore : add school admin role secondary class

Revision ID: 26f52d4c80d5
Revises: fb1c82bda872
Create Date: 2023-10-26 15:52:47.149307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f52d4c80d5'
down_revision = 'fb1c82bda872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_admin_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_role_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['school_manager.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_role_id'], ['school_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('school_user_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_user_role',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name='school_user_role_school_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_role_id'], ['school_role.id'], name='school_user_role_school_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='school_user_role_pkey')
    )
    op.drop_table('school_admin_role')
    # ### end Alembic commands ###
