"""chore : change learning group, project database archetecture

Revision ID: 2e644a7e3177
Revises: d6eafc962037
Create Date: 2023-10-25 14:53:33.048156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e644a7e3177'
down_revision = 'd6eafc962037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_role_permission', sa.Column('school_permission_id', sa.Integer(), nullable=True))
    op.drop_constraint('school_role_permission_permission_id_fkey', 'school_role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'school_role_permission', 'school_permission', ['school_permission_id'], ['id'], ondelete='CASCADE')
    op.drop_column('school_role_permission', 'permission_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_role_permission', sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'school_role_permission', type_='foreignkey')
    op.create_foreign_key('school_role_permission_permission_id_fkey', 'school_role_permission', 'permission', ['permission_id'], ['id'], ondelete='CASCADE')
    op.drop_column('school_role_permission', 'school_permission_id')
    # ### end Alembic commands ###
