"""add unique key to country & state

Revision ID: 2faedd1069e1
Revises: 68eb68bdc226
Create Date: 2023-10-07 18:26:18.026747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2faedd1069e1'
down_revision = '68eb68bdc226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'country', ['country_name'])
    op.create_unique_constraint(None, 'state', ['state_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'state', type_='unique')
    op.drop_constraint(None, 'country', type_='unique')
    # ### end Alembic commands ###
