"""refactor : remove cascade on user model for admin

Revision ID: 353670beb1f3
Revises: 6eae89c333e5
Create Date: 2023-10-14 17:53:02.381348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353670beb1f3'
down_revision = '6eae89c333e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
