"""chore : update school role, learning-group, project models

Revision ID: 363be3ed3194
Revises: 8767aba25b89
Create Date: 2023-10-23 22:25:48.114657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363be3ed3194'
down_revision = '8767aba25b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_by', sa.Integer(), nullable=False))
    op.alter_column('project', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('project_parent_id_fkey', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_column('project', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('project_parent_id_fkey', 'project', 'parent', ['parent_id'], ['id'])
    op.alter_column('project', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('project', 'created_by')
    # ### end Alembic commands ###
