"""fix : run clean up

Revision ID: 37da80d447f1
Revises: 353670beb1f3
Create Date: 2023-10-14 18:13:06.408014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37da80d447f1'
down_revision = '353670beb1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
