"""chore : add project duration

Revision ID: 3cceda07e2e9
Revises: 44ecc1f2d17e
Create Date: 2023-11-08 10:25:21.967980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cceda07e2e9'
down_revision = '44ecc1f2d17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_duration', sa.String(length=450), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_duration')
    # ### end Alembic commands ###
