"""update message model

Revision ID: 3e896e232efb
Revises: 90d3af6c684b
Create Date: 2023-12-11 07:28:18.307886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e896e232efb'
down_revision = '90d3af6c684b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
