"""refactor school teacher relationship

Revision ID: 448fe963a736
Revises: 5ab44d418c52
Create Date: 2023-10-14 09:19:21.767629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448fe963a736'
down_revision = '5ab44d418c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
