"""chore : add checklist column to projects model

Revision ID: 44ecc1f2d17e
Revises: 6fb85a365a02
Create Date: 2023-11-08 10:15:02.915607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44ecc1f2d17e'
down_revision = '6fb85a365a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('meets_project_duration', sa.String(length=450), nullable=True))
    op.add_column('project', sa.Column('is_key_knowledge', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_challenging_problem', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_sustained_inquiry', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_authentic', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_student_voice', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_reflection', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_critique', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_public_product', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.drop_column('project', 'subject_matter')
    op.drop_column('project', 'project_duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_duration', sa.VARCHAR(length=450), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('subject_matter', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('project', 'is_private')
    op.drop_column('project', 'is_public_product')
    op.drop_column('project', 'is_critique')
    op.drop_column('project', 'is_reflection')
    op.drop_column('project', 'is_student_voice')
    op.drop_column('project', 'is_authentic')
    op.drop_column('project', 'is_sustained_inquiry')
    op.drop_column('project', 'is_challenging_problem')
    op.drop_column('project', 'is_key_knowledge')
    op.drop_column('project', 'meets_project_duration')
    # ### end Alembic commands ###
