"""chore : clean up models 2

Revision ID: 4e51560216e6
Revises: afbb02a8faa1
Create Date: 2023-11-19 01:38:32.764248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e51560216e6'
down_revision = 'afbb02a8faa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
