"""refactor cascade on tables

Revision ID: 5ab44d418c52
Revises: a431dd627d88
Create Date: 2023-10-14 08:56:54.365504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab44d418c52'
down_revision = 'a431dd627d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_user_id_fkey', 'admin', type_='foreignkey')
    op.create_foreign_key(None, 'admin', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('confirmation_code_user_id_fkey', 'confirmation_code', type_='foreignkey')
    op.create_foreign_key(None, 'confirmation_code', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('parent_user_id_fkey', 'parent', type_='foreignkey')
    op.create_foreign_key(None, 'parent', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_school_id_fkey', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'school', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('report_school_id_fkey', 'report', type_='foreignkey')
    op.create_foreign_key(None, 'report', 'school', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('school_manager_user_id_fkey', 'school_manager', type_='foreignkey')
    op.drop_constraint('school_manager_school_id_fkey', 'school_manager', type_='foreignkey')
    op.create_foreign_key(None, 'school_manager', 'school', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'school_manager', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('school_parent_parent_id_fkey', 'school_parent', type_='foreignkey')
    op.drop_constraint('school_parent_school_id_fkey', 'school_parent', type_='foreignkey')
    op.create_foreign_key(None, 'school_parent', 'school', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'school_parent', 'parent', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('school_teacher_teacher_id_fkey', 'school_teacher', type_='foreignkey')
    op.drop_constraint('school_teacher_school_id_fkey', 'school_teacher', type_='foreignkey')
    op.create_foreign_key(None, 'school_teacher', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'school_teacher', 'school', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('student_school_id_fkey', 'student', type_='foreignkey')
    op.drop_constraint('student_user_id_fkey', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'school', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('subscription_plan_id_fkey', 'subscription', type_='foreignkey')
    op.drop_constraint('subscription_school_id_fkey', 'subscription', type_='foreignkey')
    op.create_foreign_key(None, 'subscription', 'subcription_plan', ['plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscription', 'school', ['school_id'], ['id'], ondelete='CASCADE')
    op.add_column('teacher', sa.Column('school_id', sa.Integer(), nullable=True))
    op.drop_constraint('teacher_user_id_fkey', 'teacher', type_='foreignkey')
    op.create_foreign_key(None, 'teacher', 'school', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('teacher_student_teacher_id_fkey', 'teacher_student', type_='foreignkey')
    op.drop_constraint('teacher_student_student_id_fkey', 'teacher_student', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_student', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_student', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_role_user_id_fkey', 'user_role', type_='foreignkey')
    op.drop_constraint('user_role_role_id_fkey', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key('user_role_role_id_fkey', 'user_role', 'role', ['role_id'], ['id'])
    op.create_foreign_key('user_role_user_id_fkey', 'user_role', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'teacher_student', type_='foreignkey')
    op.drop_constraint(None, 'teacher_student', type_='foreignkey')
    op.create_foreign_key('teacher_student_student_id_fkey', 'teacher_student', 'student', ['student_id'], ['id'])
    op.create_foreign_key('teacher_student_teacher_id_fkey', 'teacher_student', 'teacher', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_foreign_key('teacher_user_id_fkey', 'teacher', 'user', ['user_id'], ['id'])
    op.drop_column('teacher', 'school_id')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.create_foreign_key('subscription_school_id_fkey', 'subscription', 'school', ['school_id'], ['id'])
    op.create_foreign_key('subscription_plan_id_fkey', 'subscription', 'subcription_plan', ['plan_id'], ['id'])
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_user_id_fkey', 'student', 'user', ['user_id'], ['id'])
    op.create_foreign_key('student_school_id_fkey', 'student', 'school', ['school_id'], ['id'])
    op.drop_constraint(None, 'school_teacher', type_='foreignkey')
    op.drop_constraint(None, 'school_teacher', type_='foreignkey')
    op.create_foreign_key('school_teacher_school_id_fkey', 'school_teacher', 'school', ['school_id'], ['id'])
    op.create_foreign_key('school_teacher_teacher_id_fkey', 'school_teacher', 'teacher', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'school_parent', type_='foreignkey')
    op.drop_constraint(None, 'school_parent', type_='foreignkey')
    op.create_foreign_key('school_parent_school_id_fkey', 'school_parent', 'school', ['school_id'], ['id'])
    op.create_foreign_key('school_parent_parent_id_fkey', 'school_parent', 'parent', ['parent_id'], ['id'])
    op.drop_constraint(None, 'school_manager', type_='foreignkey')
    op.drop_constraint(None, 'school_manager', type_='foreignkey')
    op.create_foreign_key('school_manager_school_id_fkey', 'school_manager', 'school', ['school_id'], ['id'])
    op.create_foreign_key('school_manager_user_id_fkey', 'school_manager', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.create_foreign_key('report_school_id_fkey', 'report', 'school', ['school_id'], ['id'])
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('project_school_id_fkey', 'project', 'school', ['school_id'], ['id'])
    op.drop_constraint(None, 'parent', type_='foreignkey')
    op.create_foreign_key('parent_user_id_fkey', 'parent', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'confirmation_code', type_='foreignkey')
    op.create_foreign_key('confirmation_code_user_id_fkey', 'confirmation_code', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.create_foreign_key('admin_user_id_fkey', 'admin', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
