"""chore : update school role, learning-group, project models

Revision ID: 5d7aae4616c2
Revises: 24a14f82ec73
Create Date: 2023-10-23 18:03:47.776990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7aae4616c2'
down_revision = '24a14f82ec73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
