"""chore : add profile image to parents model

Revision ID: 5dd2dab8c601
Revises: 617aff7f92db
Create Date: 2024-04-16 17:01:39.445462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd2dab8c601'
down_revision = '617aff7f92db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'content_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('parent', sa.Column('profile_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'profile_image')
    op.alter_column('message', 'content_type',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
