"""drop sme

Revision ID: 6010c8202a4d
Revises: 9ae578ff16b8
Create Date: 2024-02-22 21:03:14.247251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6010c8202a4d'
down_revision = '9ae578ff16b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SME')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SME',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('contact_telephone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('registered_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area_of_expertise', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nin_certificate', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name='SME_school_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='SME_pkey'),
    sa.UniqueConstraint('company_name', name='SME_company_name_key'),
    sa.UniqueConstraint('email', name='SME_email_key')
    )
    # ### end Alembic commands ###
