"""chore : add content_type to file upload

Revision ID: 617aff7f92db
Revises: 6670dd5d3f2e
Create Date: 2024-04-13 23:20:49.371522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617aff7f92db'
down_revision = '6670dd5d3f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_question', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('learning_group_file', sa.Column('content_type', sa.Text(), nullable=True))
    op.add_column('project_file', sa.Column('content_type', sa.Text(), nullable=True))
    op.add_column('student_file', sa.Column('content_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_file', 'content_type')
    op.drop_column('project_file', 'content_type')
    op.drop_column('learning_group_file', 'content_type')
    op.drop_column('checklist_question', 'error')
    # ### end Alembic commands ###
