"""chore : refactor learning_group_subscription table

Revision ID: 63e0a258a676
Revises: 4ebfaae11480
Create Date: 2023-11-22 07:19:36.969853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e0a258a676'
down_revision = '4ebfaae11480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_group_subscription', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('learning_group_subscription_parent_id_fkey', 'learning_group_subscription', type_='foreignkey')
    op.create_foreign_key(None, 'learning_group_subscription', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('learning_group_subscription', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_group_subscription', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'learning_group_subscription', type_='foreignkey')
    op.create_foreign_key('learning_group_subscription_parent_id_fkey', 'learning_group_subscription', 'parent', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('learning_group_subscription', 'user_id')
    # ### end Alembic commands ###
