"""add student_parents table

Revision ID: 697ef4a49b9d
Revises: d59407a20197
Create Date: 2024-02-08 17:32:40.543535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697ef4a49b9d'
down_revision = 'd59407a20197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('parent', sa.Column('current_school', sa.String(length=350), nullable=True))
    op.add_column('parent', sa.Column('date_to_join', sa.String(length=350), nullable=True))
    op.add_column('parent', sa.Column('languages_spoken_at_home', sa.Text(), nullable=True))
    op.add_column('parent', sa.Column('child_first_language', sa.String(length=350), nullable=True))
    op.add_column('parent', sa.Column('has_emailed_child_kyc', sa.Boolean(), nullable=True))
    op.add_column('parent', sa.Column('agree_with_terms', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('emergency_contact_msisdn', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('any_allergies', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('student', sa.Column('any_special_dietary', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('special_dietary', sa.Text(), nullable=True))
    op.add_column('student', sa.Column('has_siblings', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('more_details_about_student', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'more_details_about_student')
    op.drop_column('student', 'has_siblings')
    op.drop_column('student', 'special_dietary')
    op.drop_column('student', 'any_special_dietary')
    op.drop_column('student', 'allergies')
    op.drop_column('student', 'any_allergies')
    op.drop_column('student', 'emergency_contact_msisdn')
    op.drop_column('parent', 'agree_with_terms')
    op.drop_column('parent', 'has_emailed_child_kyc')
    op.drop_column('parent', 'child_first_language')
    op.drop_column('parent', 'languages_spoken_at_home')
    op.drop_column('parent', 'date_to_join')
    op.drop_column('parent', 'current_school')
    op.drop_table('student_parent')
    # ### end Alembic commands ###
