"""feat : add transaction model

Revision ID: 6fb85a365a02
Revises: f9def52e88c5
Create Date: 2023-11-06 06:35:48.326862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb85a365a02'
down_revision = 'f9def52e88c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('fees', sa.Integer(), nullable=True),
    sa.Column('card_authorization_code', sa.String(length=200), nullable=True),
    sa.Column('card_bin', sa.String(length=20), nullable=True),
    sa.Column('card_last4', sa.String(length=10), nullable=True),
    sa.Column('card_exp_month', sa.String(length=10), nullable=True),
    sa.Column('card_exp_year', sa.String(length=50), nullable=True),
    sa.Column('card_type', sa.String(length=100), nullable=True),
    sa.Column('card_bank', sa.String(length=100), nullable=True),
    sa.Column('card_country_code', sa.String(length=50), nullable=True),
    sa.Column('card_brand', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('card_reusable', sa.Boolean(), nullable=True),
    sa.Column('card_signature', sa.String(length=200), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('customer_email', sa.String(length=150), nullable=True),
    sa.Column('customer_phone', sa.String(length=120), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
