"""feat : add project activity

Revision ID: 7030fd12f76d
Revises: 0e45d9a41061
Create Date: 2023-11-03 06:56:08.115599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7030fd12f76d'
down_revision = '0e45d9a41061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=350), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=350), nullable=True),
    sa.Column('objectives', sa.String(length=350), nullable=True),
    sa.Column('resources', sa.String(length=350), nullable=True),
    sa.Column('weblinks', sa.String(length=350), nullable=True),
    sa.Column('way_to_extend', sa.String(length=350), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['learning_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project', sa.Column('academic_year', sa.String(length=350), nullable=True))
    op.add_column('project', sa.Column('term', sa.String(length=350), nullable=True))
    op.add_column('project', sa.Column('project_type', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('project', sa.Column('subject_matter', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('project', sa.Column('age_group', sa.String(length=350), nullable=True))
    op.add_column('project', sa.Column('key_words', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('project', sa.Column('project_aim', sa.String(length=350), nullable=True))
    op.add_column('project', sa.Column('problem_to_solve', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('project', sa.Column('weblinks', sa.String(length=350), nullable=True))
    op.add_column('project', sa.Column('milestones', sa.String(length=350), nullable=True))
    op.add_column('project', sa.Column('final_product', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('project', sa.Column('learning_goals', sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'learning_goals')
    op.drop_column('project', 'final_product')
    op.drop_column('project', 'milestones')
    op.drop_column('project', 'weblinks')
    op.drop_column('project', 'problem_to_solve')
    op.drop_column('project', 'project_aim')
    op.drop_column('project', 'key_words')
    op.drop_column('project', 'age_group')
    op.drop_column('project', 'subject_matter')
    op.drop_column('project', 'project_type')
    op.drop_column('project', 'term')
    op.drop_column('project', 'academic_year')
    op.drop_table('project_activity')
    # ### end Alembic commands ###
