"""chore : update school role, learning-group, project models

Revision ID: 8767aba25b89
Revises: d7b5cf8b5402
Create Date: 2023-10-23 21:57:45.882237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8767aba25b89'
down_revision = 'd7b5cf8b5402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
