"""chore : fix issues on academic & term

Revision ID: 88aabef2a1b7
Revises: d779fb30c49b
Create Date: 2023-11-18 16:00:14.076732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88aabef2a1b7'
down_revision = 'd779fb30c49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
