"""chore : add emergency first and last name

Revision ID: 8a752ad3f1e6
Revises: 06b22b3fa353
Create Date: 2024-02-08 14:24:54.351796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a752ad3f1e6'
down_revision = '06b22b3fa353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('emergency_contact_first_name', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('emergency_contact_last_name', sa.String(length=350), nullable=True))
    op.drop_column('student', 'emergency_contact_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('emergency_contact_name', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.drop_column('student', 'emergency_contact_last_name')
    op.drop_column('student', 'emergency_contact_first_name')
    # ### end Alembic commands ###
