"""chore : change learning group, project database archetecture

Revision ID: 8be25fd5e7c9
Revises: 9887ddec3314
Create Date: 2023-10-25 14:29:56.507244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be25fd5e7c9'
down_revision = '9887ddec3314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('learning_group_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_group_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['learning_group_id'], ['learning_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_group_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['learning_group_id'], ['learning_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('learning_group_projects', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('learning_group_projects_student_id_fkey', 'learning_group_projects', type_='foreignkey')
    op.drop_constraint('learning_group_projects_teacher_id_fkey', 'learning_group_projects', type_='foreignkey')
    op.drop_column('learning_group_projects', 'student_id')
    op.drop_column('learning_group_projects', 'teacher_id')
    op.drop_constraint('school_role_name_key', 'school_role', type_='unique')
    op.create_unique_constraint('uq_school_role_name', 'school_role', ['school_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_school_role_name', 'school_role', type_='unique')
    op.create_unique_constraint('school_role_name_key', 'school_role', ['name'])
    op.add_column('learning_group_projects', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('learning_group_projects', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('learning_group_projects_teacher_id_fkey', 'learning_group_projects', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('learning_group_projects_student_id_fkey', 'learning_group_projects', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('learning_group_projects', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('learning_group_students')
    op.drop_table('teacher_project')
    op.drop_table('student_project')
    op.drop_table('learning_group_teachers')
    op.drop_table('school_permission')
    # ### end Alembic commands ###
