"""update dev db

Revision ID: 8cd6067b54c5
Revises: 2faedd1069e1
Create Date: 2023-10-07 19:17:09.487859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd6067b54c5'
down_revision = '2faedd1069e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
