"""chore : remove old checklist

Revision ID: 90c27d8eb00e
Revises: 3cceda07e2e9
Create Date: 2023-11-08 13:13:20.121705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c27d8eb00e'
down_revision = '3cceda07e2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_checklist', sa.JSON(none_as_null=True), nullable=True))
    op.drop_column('project', 'is_reflection')
    op.drop_column('project', 'is_student_voice')
    op.drop_column('project', 'is_key_knowledge')
    op.drop_column('project', 'is_authentic')
    op.drop_column('project', 'is_critique')
    op.drop_column('project', 'is_challenging_problem')
    op.drop_column('project', 'is_sustained_inquiry')
    op.drop_column('project', 'is_private')
    op.drop_column('project', 'is_public_product')
    op.drop_constraint('project_activity_project_id_fkey', 'project_activity', type_='foreignkey')
    op.create_foreign_key(None, 'project_activity', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_activity', type_='foreignkey')
    op.create_foreign_key('project_activity_project_id_fkey', 'project_activity', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('project', sa.Column('is_public_product', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('is_sustained_inquiry', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('is_challenging_problem', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('is_critique', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('is_authentic', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('is_key_knowledge', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('is_student_voice', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('is_reflection', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('project', 'project_checklist')
    # ### end Alembic commands ###
