"""refactor school teacher relationship

Revision ID: 97ccd6a19596
Revises: 00d2e113dc2e
Create Date: 2023-10-14 09:42:49.265017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ccd6a19596'
down_revision = '00d2e113dc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
