"""chore : add unique key to project & learning group

Revision ID: 9887ddec3314
Revises: 363be3ed3194
Create Date: 2023-10-24 21:11:04.168066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9887ddec3314'
down_revision = '363be3ed3194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('learning_group_name_key', 'learning_group', type_='unique')
    op.create_unique_constraint('uq_school_learning_group_name', 'learning_group', ['school_id', 'name'])
    op.alter_column('learning_group_projects', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('project_name_key', 'project', type_='unique')
    op.create_unique_constraint('uq_school_project_name', 'project', ['school_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_school_project_name', 'project', type_='unique')
    op.create_unique_constraint('project_name_key', 'project', ['name'])
    op.alter_column('learning_group_projects', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_school_learning_group_name', 'learning_group', type_='unique')
    op.create_unique_constraint('learning_group_name_key', 'learning_group', ['name'])
    # ### end Alembic commands ###
