"""remove the unique constraint in role created_by

Revision ID: a1368f6f75d0
Revises: 425786104eee
Create Date: 2023-08-31 08:13:58.447881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1368f6f75d0'
down_revision = '425786104eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_created_by_key', 'role', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('role_created_by_key', 'role', ['created_by'])
    # ### end Alembic commands ###
