"""fix role permission key

Revision ID: a2d78d8b29b1
Revises: 97ccd6a19596
Create Date: 2023-10-14 15:34:06.066984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d78d8b29b1'
down_revision = '97ccd6a19596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
