"""chore : add profile image to teacher

Revision ID: a980a8eb4a18
Revises: 6991b0a4c100
Create Date: 2024-03-09 14:11:02.007594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a980a8eb4a18'
down_revision = '6991b0a4c100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('profile_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'profile_image')
    # ### end Alembic commands ###
