"""fix role_permission 

Revision ID: aeb9b87cc099
Revises: a2d78d8b29b1
Create Date: 2023-10-14 15:36:34.333754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb9b87cc099'
down_revision = 'a2d78d8b29b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_permission_role_id_fkey', 'role_permission', type_='foreignkey')
    op.drop_constraint('role_permission_permission_id_fkey', 'role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permission', 'permission', ['permission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.create_foreign_key('role_permission_permission_id_fkey', 'role_permission', 'permission', ['permission_id'], ['id'])
    op.create_foreign_key('role_permission_role_id_fkey', 'role_permission', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###
