"""update student model

Revision ID: b4dc42e6387a
Revises: ce389c20edb3
Create Date: 2023-09-29 11:43:27.965496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dc42e6387a'
down_revision = 'ce389c20edb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'school', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'school_id')
    # ### end Alembic commands ###
