"""refactor school teacher relationship

Revision ID: b8e07569caba
Revises: 00c4a17f6cae
Create Date: 2023-10-14 09:26:41.134681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e07569caba'
down_revision = '00c4a17f6cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
