"""refactor : change project_type in project model to text

Revision ID: be40fcc56a71
Revises: 7030fd12f76d
Create Date: 2023-11-03 07:28:40.656243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be40fcc56a71'
down_revision = '7030fd12f76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
