"""refactor the application model

Revision ID: c49c88003a63
Revises: 8705106400d4
Create Date: 2023-08-30 09:57:24.824497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49c88003a63'
down_revision = '8705106400d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('first_name', sa.String(length=250), nullable=True))
    op.add_column('admin', sa.Column('last_name', sa.String(length=250), nullable=True))
    op.add_column('admin', sa.Column('country', sa.String(length=250), nullable=True))
    op.add_column('admin', sa.Column('state', sa.String(length=250), nullable=True))
    op.drop_column('admin', 'isDeactivated')
    op.drop_column('admin', 'name')
    op.drop_column('admin', 'deactivate_reason')
    op.add_column('audit', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audit', 'admin', ['admin_id'], ['id'])
    op.drop_column('parent', 'isDeactivated')
    op.drop_column('parent', 'deactivate_reason')
    op.add_column('report', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report', 'school', ['school_id'], ['id'])
    op.create_unique_constraint(None, 'role', ['name'])
    op.drop_column('school_manager', 'isDeactivated')
    op.drop_column('school_manager', 'deactivate_reason')
    op.drop_column('student', 'isDeactivated')
    op.drop_column('student', 'deactivate_reason')
    op.drop_column('teacher', 'isDeactivated')
    op.drop_column('teacher', 'deactivate_reason')
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('isDeactivated', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('deactivate_reason', sa.String(length=450), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'deactivate_reason')
    op.drop_column('user', 'isDeactivated')
    op.drop_column('user', 'role_id')
    op.add_column('teacher', sa.Column('deactivate_reason', sa.VARCHAR(length=450), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('isDeactivated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('deactivate_reason', sa.VARCHAR(length=450), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('isDeactivated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('school_manager', sa.Column('deactivate_reason', sa.VARCHAR(length=450), autoincrement=False, nullable=True))
    op.add_column('school_manager', sa.Column('isDeactivated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'school_id')
    op.add_column('parent', sa.Column('deactivate_reason', sa.VARCHAR(length=450), autoincrement=False, nullable=True))
    op.add_column('parent', sa.Column('isDeactivated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit', type_='foreignkey')
    op.drop_column('audit', 'admin_id')
    op.add_column('admin', sa.Column('deactivate_reason', sa.VARCHAR(length=450), autoincrement=False, nullable=True))
    op.add_column('admin', sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('admin', sa.Column('isDeactivated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('admin', 'state')
    op.drop_column('admin', 'country')
    op.drop_column('admin', 'last_name')
    op.drop_column('admin', 'first_name')
    # ### end Alembic commands ###
