"""chore : add back is_private

Revision ID: ce2eb4f94811
Revises: 90c27d8eb00e
Create Date: 2023-11-08 13:17:55.598851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2eb4f94811'
down_revision = '90c27d8eb00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_private')
    # ### end Alembic commands ###
