"""update teachers, students, parents model

Revision ID: ce389c20edb3
Revises: 1bd42e844ec0
Create Date: 2023-09-20 10:37:47.177714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce389c20edb3'
down_revision = '1bd42e844ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('first_name', sa.String(length=350), nullable=True))
    op.add_column('parent', sa.Column('last_name', sa.String(length=350), nullable=True))
    op.add_column('parent', sa.Column('_gender', sa.String(length=250), nullable=True))
    op.add_column('parent', sa.Column('country', sa.String(length=350), nullable=True))
    op.add_column('parent', sa.Column('state', sa.String(length=350), nullable=True))
    op.add_column('parent', sa.Column('work_email', sa.String(length=350), nullable=True))
    op.add_column('parent', sa.Column('work_msisdn', sa.String(length=350), nullable=True))
    op.drop_column('parent', 'residential_address')
    op.drop_column('parent', 'name')
    op.add_column('student', sa.Column('first_name', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('last_name', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('_gender', sa.String(length=250), nullable=True))
    op.add_column('student', sa.Column('age', sa.String(length=250), nullable=True))
    op.add_column('student', sa.Column('dob', sa.String(length=250), nullable=True))
    op.add_column('student', sa.Column('country', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('state', sa.String(length=350), nullable=True))
    op.drop_column('student', 'residential_address')
    op.drop_column('student', 'name')
    op.add_column('teacher', sa.Column('first_name', sa.String(length=350), nullable=True))
    op.add_column('teacher', sa.Column('last_name', sa.String(length=350), nullable=True))
    op.add_column('teacher', sa.Column('_gender', sa.String(length=250), nullable=True))
    op.add_column('teacher', sa.Column('country', sa.String(length=350), nullable=True))
    op.add_column('teacher', sa.Column('state', sa.String(length=350), nullable=True))
    op.drop_column('teacher', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('name', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.drop_column('teacher', 'state')
    op.drop_column('teacher', 'country')
    op.drop_column('teacher', '_gender')
    op.drop_column('teacher', 'last_name')
    op.drop_column('teacher', 'first_name')
    op.add_column('student', sa.Column('name', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('residential_address', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.drop_column('student', 'state')
    op.drop_column('student', 'country')
    op.drop_column('student', 'dob')
    op.drop_column('student', 'age')
    op.drop_column('student', '_gender')
    op.drop_column('student', 'last_name')
    op.drop_column('student', 'first_name')
    op.add_column('parent', sa.Column('name', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.add_column('parent', sa.Column('residential_address', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.drop_column('parent', 'work_msisdn')
    op.drop_column('parent', 'work_email')
    op.drop_column('parent', 'state')
    op.drop_column('parent', 'country')
    op.drop_column('parent', '_gender')
    op.drop_column('parent', 'last_name')
    op.drop_column('parent', 'first_name')
    # ### end Alembic commands ###
