"""update parents model

Revision ID: d59407a20197
Revises: e2c130c1a259
Create Date: 2024-02-05 22:01:52.983592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59407a20197'
down_revision = 'e2c130c1a259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('relationship_to_student', sa.String(length=350), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'relationship_to_student')
    # ### end Alembic commands ###
