"""chore : change learning group, project database archetecture

Revision ID: d6eafc962037
Revises: 8be25fd5e7c9
Create Date: 2023-10-25 14:38:34.270401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6eafc962037'
down_revision = '8be25fd5e7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_project', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_project', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    op.add_column('teacher_project', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher_project', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_project', type_='foreignkey')
    op.drop_column('teacher_project', 'teacher_id')
    op.drop_constraint(None, 'student_project', type_='foreignkey')
    op.drop_column('student_project', 'student_id')
    # ### end Alembic commands ###
