"""chore : remove school admin role secondary

Revision ID: e6f47cec29c7
Revises: 26f52d4c80d5
Create Date: 2023-10-26 17:27:00.646150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f47cec29c7'
down_revision = '26f52d4c80d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_admin_role')
    op.add_column('school_manager', sa.Column('school_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'school_manager', 'school_role', ['school_role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school_manager', type_='foreignkey')
    op.drop_column('school_manager', 'school_role_id')
    op.create_table('school_admin_role',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['school_manager.id'], name='school_admin_role_manager_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_role_id'], ['school_role.id'], name='school_admin_role_school_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='school_admin_role_pkey')
    )
    # ### end Alembic commands ###
