"""chore : modify project model

Revision ID: ed2333554016
Revises: 66fa9da7d27e
Create Date: 2023-11-25 18:00:43.448635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2333554016'
down_revision = '66fa9da7d27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
