"""chore : update school role, learning-group, project models

Revision ID: ed67855975b1
Revises: f1b3704a6e0e
Create Date: 2023-10-23 17:36:48.698574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed67855975b1'
down_revision = 'f1b3704a6e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_school_role_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'school_role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('school_role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_school_role_id_fkey', 'user', 'school_role', ['school_role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
