"""chore : update school role, learning-group, project models

Revision ID: f1b3704a6e0e
Revises: 4df434314207
Create Date: 2023-10-23 16:14:45.054797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b3704a6e0e'
down_revision = '4df434314207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('learning_group_students')
    op.drop_table('learning_group_teachers')
    op.add_column('learning_group', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'learning_group', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('learning_group_projects', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('learning_group_projects', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'learning_group_projects', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'learning_group_projects', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learning_group_projects', type_='foreignkey')
    op.drop_constraint(None, 'learning_group_projects', type_='foreignkey')
    op.drop_column('learning_group_projects', 'teacher_id')
    op.drop_column('learning_group_projects', 'student_id')
    op.drop_constraint(None, 'learning_group', type_='foreignkey')
    op.drop_column('learning_group', 'created_by')
    op.create_table('learning_group_teachers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('learning_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['learning_group_id'], ['learning_group.id'], name='learning_group_teachers_learning_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='learning_group_teachers_teacher_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='learning_group_teachers_pkey')
    )
    op.create_table('learning_group_students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('learning_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['learning_group_id'], ['learning_group.id'], name='learning_group_students_learning_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='learning_group_students_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='learning_group_students_pkey')
    )
    op.drop_table('project_group')
    # ### end Alembic commands ###
