"""make persmission name as unique

Revision ID: f4cf4858e7a8
Revises: c49c88003a63
Create Date: 2023-08-30 12:02:33.347655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cf4858e7a8'
down_revision = 'c49c88003a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'permission', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission', type_='unique')
    # ### end Alembic commands ###
