"""feat : add project activity

Revision ID: f9def52e88c5
Revises: 1f8af0a9a529
Create Date: 2023-11-06 03:22:41.031422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9def52e88c5'
down_revision = '1f8af0a9a529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'SME', ['company_name'])
    op.add_column('project_activity', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('project_activity', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('project_activity', sa.Column('finish_date', sa.Date(), nullable=True))
    op.add_column('project_activity', sa.Column('learning_objectives', sa.Text(), nullable=True))
    op.add_column('project_activity', sa.Column('supporting_weblinks', sa.String(length=350), nullable=True))
    op.add_column('project_activity', sa.Column('supporting_media', sa.String(length=350), nullable=True))
    op.add_column('project_activity', sa.Column('ways_to_extend', sa.Text(), nullable=True))
    op.alter_column('project_activity', 'name',
               existing_type=sa.VARCHAR(length=350),
               nullable=False)
    op.drop_constraint('project_activity_group_id_fkey', 'project_activity', type_='foreignkey')
    op.create_foreign_key(None, 'project_activity', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_activity', 'objectives')
    op.drop_column('project_activity', 'weblinks')
    op.drop_column('project_activity', 'group_id')
    op.drop_column('project_activity', 'way_to_extend')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_activity', sa.Column('way_to_extend', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.add_column('project_activity', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project_activity', sa.Column('weblinks', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.add_column('project_activity', sa.Column('objectives', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_activity', type_='foreignkey')
    op.create_foreign_key('project_activity_group_id_fkey', 'project_activity', 'learning_group', ['group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('project_activity', 'name',
               existing_type=sa.VARCHAR(length=350),
               nullable=True)
    op.drop_column('project_activity', 'ways_to_extend')
    op.drop_column('project_activity', 'supporting_media')
    op.drop_column('project_activity', 'supporting_weblinks')
    op.drop_column('project_activity', 'learning_objectives')
    op.drop_column('project_activity', 'finish_date')
    op.drop_column('project_activity', 'start_date')
    op.drop_column('project_activity', 'project_id')
    op.drop_constraint(None, 'SME', type_='unique')
    # ### end Alembic commands ###
