"""refactor school teacher relationship

Revision ID: fa7aa6854887
Revises: 448fe963a736
Create Date: 2023-10-14 09:24:21.804356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7aa6854887'
down_revision = '448fe963a736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
