"""refactor : restructure teacher_project

Revision ID: feb5237f2c46
Revises: 36f6d28c318d
Create Date: 2023-11-05 20:51:23.283662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb5237f2c46'
down_revision = '36f6d28c318d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
