"""update student table

Revision ID: ffaf29b23843
Revises: f1114e858025
Create Date: 2024-02-05 10:45:54.361504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffaf29b23843'
down_revision = 'f1114e858025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('middle_name', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('nick_name', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('current_school', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('parent_name', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('parent_email', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('how_you_knew_about_us', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('why_use_us', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('interest', sa.Text(), nullable=True))
    op.add_column('student', sa.Column('msisdn', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('parent_msisdn', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('father_name', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('father_msisdn', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('father_address', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('father_email', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('mother_name', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('mother_msisdn', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('mother_address', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('mother_email', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('any_medical_condition', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('medical_condition', sa.Text(), nullable=True))
    op.add_column('student', sa.Column('any_educational_needs', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('educational_needs', sa.Text(), nullable=True))
    op.add_column('student', sa.Column('any_learning_delay', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('learning_delay', sa.Text(), nullable=True))
    op.add_column('student', sa.Column('emergency_contact_name', sa.String(length=350), nullable=True))
    op.add_column('student', sa.Column('emergency_contact_relationship', sa.String(length=350), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'emergency_contact_relationship')
    op.drop_column('student', 'emergency_contact_name')
    op.drop_column('student', 'learning_delay')
    op.drop_column('student', 'any_learning_delay')
    op.drop_column('student', 'educational_needs')
    op.drop_column('student', 'any_educational_needs')
    op.drop_column('student', 'medical_condition')
    op.drop_column('student', 'any_medical_condition')
    op.drop_column('student', 'mother_email')
    op.drop_column('student', 'mother_address')
    op.drop_column('student', 'mother_msisdn')
    op.drop_column('student', 'mother_name')
    op.drop_column('student', 'father_email')
    op.drop_column('student', 'father_address')
    op.drop_column('student', 'father_msisdn')
    op.drop_column('student', 'father_name')
    op.drop_column('student', 'parent_msisdn')
    op.drop_column('student', 'msisdn')
    op.drop_column('student', 'interest')
    op.drop_column('student', 'why_use_us')
    op.drop_column('student', 'how_you_knew_about_us')
    op.drop_column('student', 'parent_email')
    op.drop_column('student', 'parent_name')
    op.drop_column('student', 'current_school')
    op.drop_column('student', 'nick_name')
    op.drop_column('student', 'middle_name')
    # ### end Alembic commands ###
